# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qt1TiRv6mNupr5ca1VVonR7Aph4oNFRb
"""

# toggle list1 to get output for the given other list elements
list1 = [12, -7, 5, 64, -14]
# list1 = [12, 14, -95, 3]


for num in list1:
    if num > 0:
        print(num, end=" ")